[package]
name = "substrate-lfs"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Large File Storage for Substrate"
edition = "2018"

[dependencies]
futures01 = "0.1"
libp2p = "0.12.0"
log = "0.4"
